# Generated by Django 3.2.4 on 2021-08-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='img',
        ),
    ]
