# Generated by Django 3.2.4 on 2021-08-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_remove_department_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.department'),
            preserve_default=False,
        ),
    ]
